#!/usr/bin/env node
const admin = require('firebase-admin');
const path = require('path');

const serviceAccount = require(path.join(__dirname, '..', 'serviceAccountKey.json'));
admin.initializeApp({ credential: admin.credential.cert(serviceAccount) });
const db = admin.firestore();

async function importMercato(data) {
  const batch = db.batch();
  for (const entry of data) {
    const ref = db.collection('mercato').doc();
    batch.set(ref, entry);
  }
  await batch.commit();
  console.log(`✅ ${data.length} entrées importées dans 'mercato'`);
  process.exit(0);
}

const DATA = [
  { joueur: "Yildiz",              prenom: "Kenan",        club: "Juventus",    poste: "A",  prix: 102, acheteur: "Adrien", equipe_acheteur: "Fragolas",          encheres_perdues: [{ equipe: "Hélas Verre de Rhum", prix: 88 }],                                                                         nationalite: "Turc",         saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "McTominay",           prenom: "Scott",        club: "Napoli",      poste: "MD", prix:  72, acheteur: "Paul",   equipe_acheteur: "Ousmane Lecce",     encheres_perdues: [{ equipe: "Il Campione", prix: 32 }, { equipe: "Fragolas", prix: 23 }],                                              nationalite: "Écossais",     saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Paz",                 prenom: "Nico",         club: "Como",        poste: "MO", prix:  64, acheteur: "Paul",   equipe_acheteur: "Ousmane Lecce",     encheres_perdues: [{ equipe: "Hélas Verre de Rhum", prix: 33 }, { equipe: "Fragolas", prix: 29 }],                                      nationalite: "Argentin",     saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Vlasic",              prenom: "Nikola",       club: "Torino",      poste: "MO", prix:  62, acheteur: "roman",  equipe_acheteur: "Il Campione",       encheres_perdues: [],                                                                                                                    nationalite: "Croate",       saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Davis",               prenom: "Keinan",       club: "Udinese",     poste: "A",  prix:  55, acheteur: "roman",  equipe_acheteur: "Il Campione",       encheres_perdues: [],                                                                                                                    nationalite: "Anglais",      saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Baturina",            prenom: "Martin",       club: "Como",        poste: "MD", prix:  53, acheteur: "Paul",   equipe_acheteur: "Ousmane Lecce",     encheres_perdues: [{ equipe: "Il Campione", prix: 38 }],                                                                                 nationalite: "Croate",       saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Dimarco",             prenom: "Federico",     club: "Inter",       poste: "DL", prix:  52, acheteur: "roman",  equipe_acheteur: "Il Campione",       encheres_perdues: [{ equipe: "Hélas Verre de Rhum", prix: 45 }, { equipe: "Ousmane Lecce", prix: 42 }, { equipe: "Fragolas", prix: 41 }], nationalite: "Italien",      saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Lautaro Martínez",    prenom: "Lautaro",      club: "Inter",       poste: "A",  prix:  42, acheteur: "Paul",   equipe_acheteur: "Ousmane Lecce",     encheres_perdues: [],                                                                                                                    nationalite: "Argentin",     saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Francisco Conceição", prenom: "Francisco",    club: "Juventus",    poste: "MO", prix:  41, acheteur: "Tiago",  equipe_acheteur: "Hélas Verre de Rhum", encheres_perdues: [{ equipe: "Fragolas", prix: 16 }],                                                                                 nationalite: "Portugais",    saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Douvikas",            prenom: "Fotis",        club: "Como",        poste: "A",  prix:  41, acheteur: "Adrien", equipe_acheteur: "Fragolas",          encheres_perdues: [{ equipe: "Hélas Verre de Rhum", prix: 24 }],                                                                         nationalite: "Grec",         saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Bastoni",             prenom: "Alessandro",   club: "Inter",       poste: "DC", prix:  41, acheteur: "Adrien", equipe_acheteur: "Fragolas",          encheres_perdues: [],                                                                                                                    nationalite: "Italien",      saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "De Bruyne",           prenom: "Kevin",        club: "Napoli",      poste: "MO", prix:  36, acheteur: "Paul",   equipe_acheteur: "Ousmane Lecce",     encheres_perdues: [{ equipe: "Il Campione", prix: 36 }, { equipe: "Hélas Verre de Rhum", prix: 13 }],                                  nationalite: "Belge",        saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Kean",                prenom: "Moise",        club: "Fiorentina",  poste: "A",  prix:  36, acheteur: "Tiago",  equipe_acheteur: "Hélas Verre de Rhum", encheres_perdues: [],                                                                                                                 nationalite: "Italien",      saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Akanji",              prenom: "Manuel",       club: "Inter",       poste: "DC", prix:  34, acheteur: "Adrien", equipe_acheteur: "Fragolas",          encheres_perdues: [{ equipe: "Il Campione", prix: 28 }],                                                                                 nationalite: "Suisse",       saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Malen",               prenom: "Donyell",      club: "Roma",        poste: "A",  prix:  33, acheteur: "Paul",   equipe_acheteur: "Ousmane Lecce",     encheres_perdues: [],                                                                                                                    nationalite: "Néerlandais",  saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Zielinski",           prenom: "Piotr",        club: "Inter",       poste: "MO", prix:  33, acheteur: "Tiago",  equipe_acheteur: "Hélas Verre de Rhum", encheres_perdues: [],                                                                                                                 nationalite: "Polonais",     saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Højlund",             prenom: "Rasmus",       club: "Napoli",      poste: "A",  prix:  28, acheteur: "Adrien", equipe_acheteur: "Fragolas",          encheres_perdues: [{ equipe: "Il Campione", prix: 20 }],                                                                                 nationalite: "Danois",       saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "McKennie",            prenom: "Weston",       club: "Juventus",    poste: "MO", prix:  26, acheteur: "Tiago",  equipe_acheteur: "Hélas Verre de Rhum", encheres_perdues: [],                                                                                                                 nationalite: "Américain",    saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Bremer",              prenom: "Gleison",      club: "Juventus",    poste: "DC", prix:  25, acheteur: "Tiago",  equipe_acheteur: "Hélas Verre de Rhum", encheres_perdues: [{ equipe: "Ousmane Lecce", prix: 22 }],                                                                            nationalite: "Brésilien",    saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Kempf",               prenom: "Marc Oliver",  club: "Como",        poste: "DC", prix:  25, acheteur: "Paul",   equipe_acheteur: "Ousmane Lecce",     encheres_perdues: [],                                                                                                                    nationalite: "Allemand",     saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
  { joueur: "Ndicka",              prenom: "Evan",         club: "Roma",        poste: "DC", prix:  24, acheteur: "roman",  equipe_acheteur: "Il Campione",       encheres_perdues: [{ equipe: "Fragolas", prix: 17 }],                                                                                    nationalite: "Français",     saison: "2025/2026", ligue: "Serie A", championnat: 6, tour: 1 },
];

importMercato(DATA).catch(err => { console.error('❌', err.message); process.exit(1); });
